### ISSUE TITLE
[BUG] - Checkupdate isn't working

### ISSUE THREAD

**Issue by ThiaudioTT** [ThiaudioTT/hoi4-presence#22]
**Describe the bug**

I think checkupdate isn't working somehow

**Comment by Wolfmyths** [comment]
I looked at the code and I didn't see anything wrong, but this was something that should be looked at.

https://github.com/ThiaudioTT/hoi4-presence/blob/main/src/checkupdate/checkupdate.py#L19

It's good practice to use a with statement here so it automatically closes the file once it's out of scope.

One thing you could try is import checkupdate.py and run that through the main script instead of `runRPC.bat` and see what happens there. This would also remove the need for another exe and lessen storage size.

**Comment by ThiaudioTT** [comment]
I tested this at most recent version (1.0.1) and checkupdate was working fine.

> It's good practice to use a with statement here so it automatically closes the file once it's out of scope.

You are right, this file is the most in the need of refactor right now.
<hr>

I will close this issue since there's nothing wrong.
